config = {'app_optim_lr': 0.01,
 'app_optim_n_epochs': 10,
 'appearance_embedding_dim': 32,
 'batch_size': 4096,
 'concat_features_across_scales': True,
 'contract': True,
 'data_dirs': ['/data/DATASETS/phototourism/brandenburg_gate'],
 'data_downsample': 1,
 'density_activation': 'trunc_exp',
 'device': 'cuda:0',
 'distortion_loss_weight': 0.0,
 'expname': 'contract_lr1e-2_aolr1e-2_ptv2e-4_ptvpn2e-4_dl0_dim32_appdim32_linear1l',
 'global_scale': [5, 12, 5],
 'global_translation': [0, 0, -1],
 'grid_config': [{'grid_dimensions': 2,
                  'input_coordinate_dim': 3,
                  'output_coordinate_dim': 32,
                  'resolution': [64, 64, 64]}],
 'histogram_loss_weight': 1.0,
 'linear_decoder': True,
 'linear_decoder_layers': 1,
 'logdir': './logs/brandenburg',
 'lr': 0.01,
 'multiscale_res': [1, 2, 4, 8],
 'ndc': False,
 'num_proposal_iterations': 2,
 'num_proposal_samples': [256, 128],
 'num_samples': 48,
 'num_steps': 30001,
 'optim_type': 'adam',
 'plane_tv_weight': 0.0002,
 'plane_tv_weight_proposal_net': 0.0002,
 'proposal_net_args_list': [{'num_input_coords': 3,
                             'num_output_coords': 8,
                             'resolution': [128, 128, 128]},
                            {'num_input_coords': 3,
                             'num_output_coords': 8,
                             'resolution': [256, 256, 256]}],
 'save_every': 10000,
 'save_outputs': True,
 'scene_bbox': [[-2.0, -2.0, -2.0], [2.0, 2.0, 2.0]],
 'scheduler_type': 'warmup_cosine',
 'single_jitter': False,
 'train_fp16': True,
 'use_same_proposal_network': False,
 'valid_every': 10000}
