expname: "c32_f8.32_donlysigma_sh0"
use_csrc: True

data:
  datadirs:
    - /data/DATASETS/SyntheticNerf/lego
  resolution: 512
  max_tr_frames: None
  max_ts_frames: 10

model:
  type: "single_reso"
  num_atoms: [32]
  coarse_reso: 32
  fine_reso: [8]
  noise_std: 0.0
  efficient_dict: False

optim:
  batch_size: 4000
  batches_per_epoch: 400
  num_epochs: 100
  lr: 2e-2
  cosine: True
  train_fp16: False
  regularization:
    l1_weight: 0.0
    tv_weight: 0.00
    consistency_weight: 0.0

sh:
  degree: 0
