expname: "test_ray_norm"
use_csrc: True 

data:
  datadirs:
    - /data/DATASETS/SyntheticNerf/lego
    - /data/DATASETS/SyntheticNerf/chair
    - /data/DATASETS/SyntheticNerf/drums
    - /data/DATASETS/SyntheticNerf/ficus
  resolution: 256
  max_tr_frames: None
  max_ts_frames: 10

model:
  num_atoms: [64]
  coarse_reso: 64
  fine_reso: [4]
  noise_std: 0.0

optim:
  batch_size: 4000
  batches_per_epoch: 400
  num_epochs: 40
  lr: 1e-2
  cosine: True
  regularization:
    l1_weight: 0.0
    tv_weight: 0.0
    consistency_weight: 0.0

sh:
  degree: 2
