expname: "learnablehash_lego_256_lowrank"
seed: 1299

data:
  datadir: "/data/DATASETS/SyntheticNerf/lego"
  resolution: 512
  downsample: 1
  max_tr_frames: 100
  max_ts_frames: 10

model:
  resolution: 256
  learnable_hash: True
  num_features: 512
  feature_dim: 32
  second_G: False
  grid_dim: 3
  lowrank_learnable_hash: True
  rank: 10

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 2e-3
  cosine: False
  train_f16: True
  samples_per_voxel: 2

sh:
  degree: 0
