expname: "e2"

data:
  datadir:
    - /data/DATASETS/SyntheticNerf/lego
    - /data/DATASETS/SyntheticNerf/chair
    - /data/DATASETS/SyntheticNerf/drums
    - /data/DATASETS/SyntheticNerf/ficus
  resolution: 256
  max_tr_frames: 10
  max_ts_frames: 10

model:
  num_atoms: 128
  coarse_reso: 64
  fine_reso: 3

regularization:
  l1_weight: 0.1
