expname: "learnablehash_lego_128_staticGnocolor_lininterp_stdgunif"

data:
  datadir: "/data/DATASETS/SyntheticNerf/lego"
  resolution: None
  max_tr_frames: 100
  max_ts_frames: 10

model:
  resolution: 256
  learnable_hash: True
  num_features: 65
  feature_dim: 32

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 2e-3
  cosine: False
  train_f16: True

sh:
  degree: 0
