expname: "tensorrf_fixintrs"

data:
  datadir: /data/DATASETS/SyntheticNerf/lego
  max_tr_frames: None
  max_ts_frames: 10

model:
  reso_init: 128
  reso_final: 300
  n_rgb_comp: [48, 48, 48]
  n_sigma_comp: [16, 16, 16]

optim:
  batch_size: 4096
  lr_init_spatial: 2e-2
  lr_init_network: 1e-3
  upsample_iters: [2000, 3000, 4000, 5500, 7000]

sh:
  degree: 2
