expname: "learnablehash_lego_128_lowrank"
seed: 1299

data:
  datadir: ["/data/DATASETS/SyntheticNerf/chair"]
  resolution: 256
  downsample: 1.562
  max_tr_frames: 25
  max_ts_frames: 10

model:
  resolution: 128
  num_features: 4096
  feature_dim: 32
  second_G: False
  grid_dim: 4
  type: "lowrank_learnable_hash"
  rank: 20

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 2e-3
  cosine: False
  train_f16: True
  samples_per_voxel: 2

sh:
  degree: 0
