expname: "e2"

data:
  datadirs:
    - /data/DATASETS/SyntheticNerf/lego
    - /data/DATASETS/SyntheticNerf/chair
    - /data/DATASETS/SyntheticNerf/drums
    - /data/DATASETS/SyntheticNerf/ficus
  resolution: 256
  max_tr_frames: None
  max_ts_frames: 10

model:
  num_atoms: 128
  coarse_reso: 64
  fine_reso: 4

optim:
  batch_size: 2000
  max_steps: 20000
  lr: 1e-2
  regularization:
    l1_weight: 0.1

sh:
  degree: 1
