expname: "plenoxel_lego_256"

data:
  datadir: "/data/DATASETS/SyntheticNerf/lego"
  resolution: 512
  max_tr_frames: None
  max_ts_frames: None

model:
  resolution: 256

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 3e-2
  cosine: True
  train_f16: False
  
sh:
  degree: 0
