expname: "lego_c64_f4.128_reusedict_lr1e-1"
use_csrc: True

data:
  datadirs:
    # - /data/datasets/nerf/data/nerf_synthetic/ship
    # - /data/datasets/nerf/data/nerf_synthetic/mic
    # - /data/datasets/nerf/data/nerf_synthetic/materials
    # - /data/datasets/nerf/data/nerf_synthetic/hotdog
    - /data/datasets/nerf/data/nerf_synthetic/lego
    # - /data/datasets/nerf/data/nerf_synthetic/chair
    # - /data/datasets/nerf/data/nerf_synthetic/drums
    # - /data/datasets/nerf/data/nerf_synthetic/ficus
  resolution: None
  max_tr_frames: None
  max_ts_frames: 10

model:
  num_atoms: [128]
  coarse_reso: 64
  fine_reso: [4]
  noise_std: 0.0

optim:
  batch_size: 4000
  batches_per_epoch: 400 # From each scene
  num_epochs: 10
  lr: 1e-1
  cosine: False
  regularization:
    l1_weight: 0.0
    tv_weight: 0.0
    consistency_weight: 0.0
  
sh:
  degree: 0
