expname: "reso32_finereso2,4,8,16_l1_0_tv_1"
use_csrc: True

data:
  datadirs:
    - /data/datasets/nerf/data/nerf_synthetic/lego
    - /data/datasets/nerf/data/nerf_synthetic/chair
    - /data/datasets/nerf/data/nerf_synthetic/drums
    - /data/datasets/nerf/data/nerf_synthetic/ficus
  resolution: 256
  max_tr_frames: None
  max_ts_frames: 10

model:
  num_atoms: [16, 32, 32, 64]
  coarse_reso: 32
  fine_reso: [2, 4, 8, 16]
  noise_std: 0.0

optim:
  batch_size: 4000
  batches_per_epoch: 100
  num_epochs: 5
  lr: 1e-2
  regularization:
    l1_weight: 0.0
    tv_weight: 1.0
    consistency_weight: 0.0

sh:
  degree: 0
