expname: "plenoxel_lego_512"

data:
  datadir: "/data/datasets/nerf/data/nerf_synthetic/lego"
  resolution: None
  max_tr_frames: None
  max_ts_frames: None

model:
  resolution: 512

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 3e-2
  cosine: True
  
sh:
  degree: 0
