expname: "c64_f2.64,4.64_c2f"
use_csrc: True

data:
  datadirs:
    - /data/datasets/nerf/data/nerf_synthetic/lego
    - /data/datasets/nerf/data/nerf_synthetic/chair
    - /data/datasets/nerf/data/nerf_synthetic/drums
    - /data/datasets/nerf/data/nerf_synthetic/ficus
  resolution: None
  max_tr_frames: None
  max_ts_frames: 10

model:
  num_atoms: [64, 64]
  coarse_reso: 64
  fine_reso: [2, 4]
  noise_std: 0.0

optim:
  batch_size: 2500
  batches_per_epoch: 400 # From each scene
  num_epochs: 100
  lr: 1e-2
  cosine: False
  regularization:
    l1_weight: 0.0
    tv_weight: 0.0
    consistency_weight: 0.0
  

sh:
  degree: 0
