expname: "c64_f2.42_f4.43_f8.43_sh2"
use_csrc: True

data:
  datadirs:
    - /data/datasets/nerf/data/nerf_synthetic/lego
    - /data/datasets/nerf/data/nerf_synthetic/chair
    - /data/datasets/nerf/data/nerf_synthetic/drums
    - /data/datasets/nerf/data/nerf_synthetic/ficus
  resolution: 512
  max_tr_frames: None
  max_ts_frames: 10

model:
  num_atoms: [42, 43, 43]
  coarse_reso: 64
  fine_reso: [2, 4, 8]
  noise_std: 0.0

optim:
  batch_size: 4000
  batches_per_epoch: 400 # From each scene
  num_epochs: 40
  lr: 1e-2
  cosine: False
  regularization:
    l1_weight: 0.0
    tv_weight: 0.0
    consistency_weight: 0.0

sh:
  degree: 2
