expname: "learnablehash_lego_128_staticGnocolor"

data:
  datadir: "/data/datasets/nerf/data/nerf_synthetic/lego"
  resolution: None
  max_tr_frames: 25
  max_ts_frames: 10

model:
  resolution: 128
  learnable_hash: True
  num_features: 10000
  feature_dim: 32

optim:
  batch_size: 4000
  num_epochs: 100
  lr: 2e-3
  cosine: False
  train_f16: True
  
sh:
  degree: 0
