config = {'add_rank_steps': [-1],
 'batch_size': 4096,
 'data_dirs': ['/home/sfk/data/dnerf/data/lego'],
 'data_downsample': 2.0,
 'density_activation': 'trunc_exp',
 'density_field_rank': 1,
 'density_field_resolution': [128, 256],
 'density_model': 'triplane',
 'expname': 'lego',
 'floater_loss': 0.0,
 'grid_config': '\n'
                '[\n'
                '    {\n'
                '        "input_coordinate_dim": 4,\n'
                '        "output_coordinate_dim": 64,\n'
                '        "grid_dimensions": 2,\n'
                '        "resolution": [64, 64, 64, 50],\n'
                '        "rank": 1,\n'
                '    },\n'
                ']\n',
 'histogram_loss_weight': 1.0,
 'isg': False,
 'isg_step': -1,
 'ist_step': -1,
 'keyframes': False,
 'l1_appearance_planes_reg': 0.001,
 'l1_plane_color_reg': 0,
 'l1_plane_density_reg': 0,
 'l1density_weight': 0,
 'logdir': './logs/dnerf',
 'lr': 0.01,
 'max_test_cameras': None,
 'max_test_tsteps': None,
 'max_train_cameras': None,
 'max_train_tsteps': None,
 'multiscale_res': [1, 2, 4],
 'n_intersections': 48,
 'num_proposal_samples': [256, 96],
 'num_steps': 10001,
 'optim_type': 'adam',
 'plane_tv_weight': 0.02,
 'proposal_decoder_type': 'nn',
 'proposal_feature_dim': 10,
 'raymarch_type': 'fixed',
 'save_every': 10000,
 'save_outputs': True,
 'save_video': True,
 'scheduler_type': 'warmup_cosine',
 'sh': False,
 'sh_decoder_type': 'manual',
 'single_jitter': False,
 'time_smoothness_weight': 0.05,
 'train_fp16': True,
 'upsample_time_resolution': [150],
 'upsample_time_steps': [-1],
 'use_F': False,
 'use_trainable_rank': False,
 'valid_every': 10000,
 'volume_tv_npts': 1024,
 'volume_tv_weight': 0.0,
 'volume_tv_what': 'Gcoords'}