expname: "learnablehash_lego_v0"

data:
  datadir: "/data/datasets/nerf/data/nerf_synthetic/lego"
  resolution: None
  max_tr_frames: None
  max_ts_frames: 10

model:
  resolution: 256
  learnable_hash: True
  num_features: 10000
  feature_dim: 32

optim:
  batch_size: 4000
  num_epochs: 50
  lr: 1e-2
  cosine: False
  train_f16: True
  
sh:
  degree: 0
