expname: "learnablehash_lego_256"

data:
  datadir: "/data/datasets/nerf/data/nerf_synthetic/lego"
  resolution: None
  max_tr_frames: 100
  max_ts_frames: 10

model:
  resolution: 256
  learnable_hash: True
  num_features: 5000
  feature_dim: 32

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 2e-3
  cosine: True
  train_f16: False
  
sh:
  degree: 0
