expname: "lowranklearnablehash"

data:
  datadir: "/data/datasets/nerf/data/nerf_synthetic/lego"
  resolution: 800
  downsample: 1
  max_tr_frames: 100
  max_ts_frames: 10

model:
  resolution: 128
  learnable_hash: False
  lowrank_learnable_hash: True
  num_features: 513
  feature_dim: 32
  second_G: False
  rank: 20

optim:
  batch_size: 4000
  num_epochs: 10
  lr: 2e-3
  cosine: False
  train_f16: True
  samples_per_voxel: 6
  
sh:
  degree: 0
