# Transfer configs must not change anything about the model

expname: "c32_f2.32,4.32_c2f_consistency0.1_k1_transfer"
use_csrc: False

data:
  datadirs:
    - /data/datasets/nerf/data/nerf_synthetic/ship
    - /data/datasets/nerf/data/nerf_synthetic/mic
    - /data/datasets/nerf/data/nerf_synthetic/materials
    - /data/datasets/nerf/data/nerf_synthetic/hotdog
  resolution: None
  max_tr_frames: None
  max_ts_frames: 10

optim:
  batch_size: 2500
  batches_per_epoch: 400 # From each scene
  num_epochs: 30
  lr: 1e-2
  cosine: False
  regularization:
    l1_weight: 0.0
    tv_weight: 0.0
    consistency_weight: 0.0

