config = {"batch_size": 4096,
 'concat_features_across_scales': True,
 'contract': False,
 'data_dirs': ['data/nerf_synthetic/lego'],
 'data_downsample': 1.0,
 'density_activation': 'trunc_exp',
 'device': 'cuda:0',
 'distortion_loss_weight': 0.001,
 'expname': 'lego_hybrid',
 'grid_config': [{'grid_dimensions': 2,
                  'input_coordinate_dim': 3,
                  'output_coordinate_dim': 32,
                  'resolution': [64, 64, 64]}],
 'histogram_loss_weight': 1.0,
 'linear_decoder': False,
 'logdir': './logs/syntheticstatic',
 'lr': 0.01,
 'max_test_cameras': None,
 'max_test_tsteps': None,
 'max_train_cameras': None,
 'max_train_tsteps': None,
 'multiscale_res': [1, 2, 4, 8],
 'ndc': False,
 'ndc_far': 0,
 'near_scaling': 0,
 'num_batches_per_dset': 1,
 'num_proposal_iterations': 2,
 'num_proposal_samples': [256, 128],
 'num_samples': 48,
 'num_steps': 30001,
 'optim_type': 'adam',
 'plane_tv_weight': 0.01,
 'plane_tv_weight_proposal_net': 0.0001,
 'proposal_net_args_list': [{'num_input_coords': 3,
                             'num_output_coords': 8,
                             'resolution': [64, 64, 64]},
                            {'num_input_coords': 3,
                             'num_output_coords': 8,
                             'resolution': [128, 128, 128]}],
 'save_every': 30000,
 'save_outputs': True,
 'scheduler_type': 'warmup_cosine',
 'single_jitter': False,
 'time_smoothness_weight': 0,
 'time_smoothness_weight_proposal_net': 0,
 'train_fp16': True,
 'use_same_proposal_network': False,
 'valid_every': 30000}